# -*- coding: utf-8 -*-
"""D3_Warmup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11QFzyJi-ZlLluCx5_MLdZtHKNYevzN2m
"""

from google.colab import drive
drive.mount("/content/gdrive")

# Commented out IPython magic to ensure Python compatibility.
# %cd gdrive/My\ Drive/Data
!ls

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import networkx as nx
import matplotlib.pyplot as plt

nodes = set()
edges = []
with open('out.ucidata-zachary','r') as f:
  for i,line in enumerate(f):
    if line[0] != '%':
      edge = line.split()
      edges.append(tuple(edge))
      nodes.add(edge[0])
      nodes.add(edge[1])

print(len(nodes))
print(len(edges))

G = nx.Graph()

G.add_nodes_from(nodes)
G.add_edges_from(edges)

nx.draw(G, with_labels=True, font_weight='bold')